#!/usr/bin/env bash

if [[ "$TRAVIS_PULL_REQUEST" != "false" ||
      ("$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != backport/*) ]]
then exit
fi

git config --global user.email "builds@travis-ci.com"
git config --global user.name "Travis CI"
TAG=v$VERSION
git tag $TAG -a -m "Quasar S3 Connector $VERSION"
git push origin $TAG
export TRAVIS_TAG=v$VERSION
